name: web_portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.2
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^1.1.2
  lottie: ^1.1.0
  responsive_framework: ^0.0.14
  smooth_page_indicator: ^0.2.0
  url_launcher: ^6.0.9
  velocity_x: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/reapet/
    - assets/keyless/
    - assets/chatapp/
    - assets/lgn/
    - assets/labouronline/
    - assets/anims/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-Light.ttf
          weight: 300
        - asset: fonts/Oswald-Bold.ttf
          weight: 900

    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Light.ttf
          weight: 300
        - asset: fonts/Lato-Bold.ttf
          weight: 900
