name: rashidwassan
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.0.2
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^9.1.0
  lottie: ^1.1.0
  responsive_framework: ^0.0.14
  smooth_page_indicator: ^0.2.0
  url_launcher: ^6.0.9
  velocity_x: ^3.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/reapet/
    - assets/keyless/
    - assets/chatapp/
    - assets/lgn/
    - assets/labouronline/
    - assets/anim/
    - assets/fonts/
    - assets/icons/


  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 900
        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300
